// <auto-generated />
namespace BookStore.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Single_Book_Genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Single_Book_Genre));
        
        string IMigrationMetadata.Id
        {
            get { return "202208011226274_Single_Book_Genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
